### ISSUE TITLE
Embed Calendar to Note

### ISSUE THREAD

**Issue by sigrunixia** [javalent/the-calendarium#15]
For @zaksquatch

Hello,

I have a few different calendars I'm using and would like to put the contents of them in a single note. That way I could jump between them in an organized way.

Is there a way to do this?

For @Yilmas

If this was implemented, or some variation of it. We would also be able to serve the calendar into a canvas.

- [x] Yay
- [ ] Nay
- [ ] Implemented

**Comment by sigrunixia** [comment]
This had the good first issue in the other repo, so adding it here.

**Comment by zaksquatch** [comment]
I'm interested to see where this goes! 🤓🧙‍♂️

**Comment by ebullient** [comment]
Are you looking for a way to generate (or regenerate) the content of a note based on events present in the calendar? As a list? As a Calendar view?

Would you want this to be a command-driven periodic content update, or a dataview style query? (If dates are in front-matter, you could probably write a dataview query right now against existing notes)

**Comment by valentine195** [comment]
I understand this to be a Calendar in a note (using a codeblock for example).

**Comment by Yilmas** [comment]
> 

Correct, this is nothing more than allowing the calendar to be displayed within a note, rather than the sidebar. 
Having it in a note, allows us to also serve it in a canvas, without any further development (crossed fingers).

**Comment by valentine195** [comment]
closed by 957a358dc851ee3a4a8ccf468f5dd549ee0f2155
