### ISSUE TITLE
[Suggestion]: Disable Theme Option

### ISSUE THREAD

**Issue by ProStashio** [javalent/the-calendarium#37]
I use some special ITS Settings that make bubbles around my headers. This causes issue in some plugins and I was hoping to get a toggle so I don't get this in the Calendar

![image](https://github.com/javalent/the-calendarium/assets/19267479/93f440ec-8b43-438d-a42e-490d844c9eb6)

**Comment by sigrunixia** [comment]
Ah, looks like we need to do some CSS here as well. This should be easy enough to do.

**Comment by valentine195** [comment]
I am sorry, but I cannot realistically disable CSS from being applied by themes.
