### ISSUE TITLE
[Bug]: Year View

### ISSUE THREAD

**Issue by ProStashio** [javalent/the-calendarium#38]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

I would expect the selection tab for Day/Week/Month/Year to be sticky so we can always see them

### Current behaviour

I may be incorrect, but they are currently not working like that

https://i.gyazo.com/8c3061016e0914865aeaa9b018e25f51.mp4

### Reproduction

Swap to year

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

1.0.1-b10

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by JenPalsKitchen** [comment]
Hello, I think this may be the most relevant bug in relation to my question - I searched the documentation and I see 
" If in Year view, it navigates back one year.
Today will reset the calendar to show where TODAY is in relation to your chosen option in 2." 

I expected it in year view if I scroll to another month, that it would scroll to have "today" in the visible window when selecting the today button. (similarly if you change years, then hit today it does bring you back to the current year, but does not center "today" in the visible section of the calendar). Is this something you would expect or would this be best added as a feature request?
