### ISSUE TITLE
[Bug]: Day View throwing exceptions

### ISSUE THREAD

**Issue by Yilmas** [javalent/the-calendarium#40]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

To open day view and show events of the day.

### Current behaviour

When you click "Day" or "Open Day" the plugin crashes, afterwhich it requires an Obsidian reload to get it working again. 

Please note that I'm using a custom calendar. (In case it matters.

### Reproduction

This is after clicking "Day".
![image](https://github.com/javalent/the-calendarium/assets/6323003/04bf1893-7d63-4bca-af03-fa9a380ba24b)

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5, 1.1.16

### Plugin Version

1.0.0-b11

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by sigrunixia** [comment]
This may be fixed in #41

**Comment by Yilmas** [comment]
Can confirm, #41 has fixed this issue.
