### ISSUE TITLE
[Bug]: Moon Cycle length input turns red if value is not an interger

### ISSUE THREAD

**Issue by Suleiman212** [javalent/the-calendarium#43]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

Cycle length input should remain the same color whether a whole number or decimal is inputted.

### Current behaviour

Cycle length input turns red when a decimal is inputted.

### Reproduction

1. Open Moon menu in calendar editing menu.
2. Input an integer, followed by a decimal point, and add numbers past the decimal point.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.3.5

### Plugin Version

b12

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by valentine195** [comment]
@Suleiman212 I can't recreate this issue. Does it happen on the default theme?

I don't do any validation on this input other than setting it to a number type, which allows decimals.

**Comment by Suleiman212** [comment]
It happens on default theme, but I messed around and tested things out and realized it's cause by a conflict with... AidenLx's Folder Note v0.16.5??  Sorry for the false alarm. No idea why that plugin would cause that behavior.

This is how it looks on default theme:

![Cycle white](https://github.com/javalent/the-calendarium/assets/31191738/5697d4f2-b643-42bf-ad16-53bb58b8405e)

![Cycle red](https://github.com/javalent/the-calendarium/assets/31191738/82d86bcf-a081-4fb3-b63c-0d6f670ce84c)

**Comment by Suleiman212** [comment]
But it seems like it's just a visual bug, there's no impact on how the moons are actually calculated, and it only occurs with that other random plugin activated, so sorry for the erroneous bug report or wasting your time.

**Comment by valentine195** [comment]
Weird! I might dig through their code to see how it’s setting that. Closing the issue though
