### ISSUE TITLE
📓 Question regarding calendarium and fantasy calendar

### ISSUE THREAD

**Issue by Foxomat** [javalent/the-calendarium#54]
### What are we changing or adding?

- [ ] Repository
- [ ] [Publish Documentation](https://plugins.javalent.com/)

### Location

.

### The issue is...

Will this plugin replace fantasy calendar or will the development of both continue? If it's the latter, what distinguishes those two?

Sorry for this, I'm sure this is the wrong place to ask but I've searched for too long and didn't find an answer and also did't find a better spot to ask this...

### Suggestions?

.

### Anything else?

.

**Comment by sigrunixia** [comment]
Hi There! Calendarium is meant to be a replacement of FC Calendar. 

So, to make a complex situation simple, here is what is going on:
- Javalent made the original FC plugin.
- The devs of FC-Calendar on the web, wanted the FC plugin brought under their umbrella for branding purposes.
- However, little if any assistance was given by the FC devs for the FC plugin, and it was an administrative process to get things done and updated.
- So, Javalent separated from that situation, and rebuilt most of the plugin under Calendarium. It will support all the existing features of FC Calendar, and then some. 
- As far as we know, the FC-Plugin is unlikely to be updated. It is out of our control as it is. 

Does that help?

**Comment by Foxomat** [comment]
> Calendarium is meant to be a replacement of FC Calendar.

That's all I needed to know! Thanks a lot!
