### ISSUE TITLE
🧩 Move Intercalary Setting

### ISSUE THREAD

**Issue by sigrunixia** [javalent/the-calendarium#55]
### Scope

As discussed, we determined it was better to move the option "Show Intercalary Months Separately" option. Some Calendars may benefit from one layout type over another. 

### Discovery

Show Intercalary Months Separately will be moved from global plugin settings, to individual calendar settings. 

### Validate

This _should_ be a simple move, but will need to check it out.

**Comment by valentine195** [comment]
This was closed with 1.0.0-b29
