### ISSUE TITLE
🐞 Date keeps reverting

### ISSUE THREAD

**Issue by ProStashio** [javalent/the-calendarium#84]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

When I set a date, it should stay on that until I change it and it should remember it.

### Current behaviour

Every so often I notice the date keeps resetting to the previous date I had set.

### Reproduction

Set to a new date, and open & reclose a bunch of times. I only notice it now and then.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.4.14

### Plugin Version

Current (I don't see a version number)

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by Co0nmz** [comment]
can confirm.
