### ISSUE TITLE
Issue with Editing and Deleting Events

### ISSUE THREAD

**Issue by aeqbea** [javalent/the-calendarium#89]
### Check for existing bug reports before submitting.

- [X] I searched for existing Bug Reports and found no similar reports.

### Expected Behavior

After creating an event, it can be right-clicked to open a sub-menu and either edited Via the "Edit Event"-Button or deleted vie the "Delete Event"-Button

### Current behaviour

A created Event cannot be edited or deleted, Clicking either button does nothing
![image](https://github.com/javalent/the-calendarium/assets/158774893/4365f29e-9d4b-488b-be7d-557d84e5b1e6)

### Reproduction

1. Right click on a day in the calendar
2. Create new event
3. Enter Name of the Event
4. Save
5. The Event appears in the calendar
6. Right-Click the Event
7. Select either "Edit Event"-Button or "Delete Event"-Button

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version Check

1.5.3

### Plugin Version

1.0.0-b30

### Confirmation

- [X] I have disabled all other plugins and the issue still persists.

**Comment by Sparks01** [comment]
Same issue on Mac.

**Comment by valentine195** [comment]
Fixed in v1.0.0
